### PR TITLE
fix: add missing slash after port in registry proxy URL replacement

### LINKED ISSUE #3379: vcluster registry proxy missing first slash in URL after port
### What happened?

An error occurs when trying to push a container to the registry proxy using `docker push`, running the proxy with `vcluster registry proxy --port 5000`:

```
docker push localhost:5000/test-image:latest 
The push refers to repository [localhost:5000/test-image]
unable to parse location http://127.0.0.1:5000v2/test-image/blobs/uploads/3dee169f-4f3a-4ac1-b7be-a3e9ba7138aa?_state=UvQ6qDzWP6mHh-KQlWhL_ZxF9Na83EMm3jHnfRrV8GN7Ik5hbWUiOiJ0ZXN0LWltYWdlIiwiVVVJRCI6IjNkZWUxNjlmLTRmM2EtNGFjMS1iN2JlLWEzZTliYTcxMzhhYSIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAyNS0xMS0yOVQyMDoyNzo0Mi45ODkwMTMwMTNaIn0%3D: parse "http://127.0.0.1:5000v2/test-image/blobs/uploads/3dee169f-4f3a-4ac1-b7be-a3e9ba7138aa?_state=UvQ6qDzWP6mHh-KQlWhL_ZxF9Na83EMm3jHnfRrV8GN7Ik5hbWUiOiJ0ZXN0LWltYWdlIiwiVVVJRCI6IjNkZWUxNjlmLTRmM2EtNGFjMS1iN2JlLWEzZTliYTcxMzhhYSIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAyNS0xMS0yOVQyMDoyNzo0Mi45ODkwMTMwMTNaIn0%3D": invalid port ":5000v2" after host
```

This also happens without a custom `--port` using the default `15000`:

```
unable to parse location http://127.0.0.1:15000v2/test-image/blobs/uploads/f579170e-7fdf-48be-b106-f7298d8ff528?_state=n2e9tBsHGVpLEFY5KKPrBiFeszbWKaoXoOXRzo6r-0d7Ik5hbWUiOiJ0ZXN0LWltYWdlIiwiVVVJRCI6ImY1NzkxNzBlLTdmZGYtNDhiZS1iMTA2LWY3Mjk4ZDhmZjUyOCIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAyNS0xMS0yOVQyMDozMjoxMi44Nzg2MDIzNDdaIn0%3D: parse "http://127.0.0.1:15000v2/test-image/blobs/uploads/f579170e-7fdf-48be-b106-f7298d8ff528?_state=n2e9tBsHGVpLEFY5KKPrBiFeszbWKaoXoOXRzo6r-0d7Ik5hbWUiOiJ0ZXN0LWltYWdlIiwiVVVJRCI6ImY1NzkxNzBlLTdmZGYtNDhiZS1iMTA2LWY3Mjk4ZDhmZjUyOCIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAyNS0xMS0yOVQyMDozMjoxMi44Nzg2MDIzNDdaIn0%3D": invalid port ":15000v2" after host
```

It appears to be caused by a missing slash between the port number `5000` and the registry API prefix `v2`.

### What did you expect to happen?

Container to be pushed successfully to the registry.

### How can we reproduce it (as minimally and precisely as possible)?

- Set `controlPlane.advanced.registry.enabled` to `true` in `vcluster.yaml`
- Run `vcluster registry proxy --port=5000 &`
- With a minimal Docker container (`echo 'FROM scratch' > Dockerfile`), build, tag `localhost:5000/test-image:latest`, and push

### Anything else we need to know?

This of course can't be fixed by adding a slash to the `--port` flag:

```
20:30:30 fatal invalid argument "5000/" for "--port" flag: strconv.ParseInt: parsing "5000/": invalid syntax
```

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.31.12
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.31.13
```

</details>

### vcluster version

<details>

```console
$ vcluster --version
vcluster version 0.30.0
```

</details>

### VCluster Config

<details>

```
controlPlane:
  advanced:
    registry:
      enabled: true
  statefulSet:
    persistence:
      volumeClaim:
        retentionPolicy: Delete
        size: 50Gi
integrations:
  metricsServer:
    enabled: true
networking:
  advanced:
    fallbackHostCluster: true
sync:
  toHost:
    ingresses:
      enabled: true
  fromHost:
    ingressClasses:
      enabled: true
    nodes:
      enabled: true
```

</details>

### PR DESCRIPTION
**Pull request by mayooot**
**What issue type does this pull request address?** (keep at least one, remove the others) 
/kind bugfix

**What does this pull request do? Which issues does it resolve?** (use `resolves #<issue_number>` if possible) 
resolves #3379

---

> [!NOTE]
> Ensures correct URL rewriting in the registry reverse proxy to avoid malformed paths and redirects.
> 
> - Refactors inline `replaceHost` into `newHostRewriter` to consistently rewrite `target` to `http://<newHost>/`
> - Updates replacement to include a trailing slash after the port (e.g., `http://127.0.0.1:15000/`)
> - Adds `proxy_test.go` with `TestNewHostRewriterAddsSlashAfterPort` to verify the rewrite behavior
> - Applies the new rewriter in `proxy.go` via `rewriteHeaderTransport.replaceHost`
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 4283137aa059d3df6d6edb30aa62590ab874c844. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: cmd/vclusterctl/cmd/registry/proxy.go [hunk 1]
```diff
@@ -90,7 +90,7 @@ func startReverseProxy(restConfig *rest.Config, port int, log log.Logger) error
 		RoundTripper: transport,
 		replaceHost: func(host string) string {
 			// we need to replace the target host with the new host
-			host = strings.Replace(host, target.String(), "http://"+newHost, -1)
+			host = strings.Replace(host, target.String(), "http://"+newHost+"/", -1)
```
Comment (cbron) [inline cmd/vclusterctl/cmd/registry/proxy.go]: Thanks for PR! Can you add some unit tests here to show both cases. You can split into method below.

Comment (mayooot) [reply cmd/vclusterctl/cmd/registry/proxy.go]: OK, I got it. Please review this.

File: cmd/vclusterctl/cmd/registry/proxy.go [hunk 2]
```diff
@@ -182,6 +176,16 @@ type rewriteHeaderTransport struct {
 	replaceHost func(string) string
 }
 
+func newHostRewriter(target *url.URL, newHost string) func(string) string {
```
Comment (rlmcpherson) [inline cmd/vclusterctl/cmd/registry/proxy.go:179]: Is it necessary to break out this function? It seems the change can be isolated to adding the `/` after newHost in the string replacement. Could you refactor this to keep the func defined at `replaceHost:`

Comment (cbron) [reply cmd/vclusterctl/cmd/registry/proxy.go:179]: Oh, I asked him to do that so he could add tests. If we can add tests easily without breaking out thats fine.

Comment (rlmcpherson) [reply cmd/vclusterctl/cmd/registry/proxy.go:179]: Oh, sorry for the confusion. This does simplify unit testing.

File: cmd/vclusterctl/cmd/registry/proxy.go (hunk 1 above)
Comment (rlmcpherson) [reply cmd/vclusterctl/cmd/registry/proxy.go]: Tests look ok, thanks.
