### PR TITLE
fixed etcd ha not coming up

### LINKED ISSUE #1365: Fresh installation of 0.17.0 k8s fails due to tls certificates on EKS
### What happened?

etcd doesn't start due to the error:

```
{"level":"info","ts":"2023-11-20T19:30:33.409521Z","caller":"embed/etcd.go:278","msg":"now serving peer/client/metrics","local-member-id":"1d1c77e4faa2d414","initial-advertise-peer-urls":["https://test-etcd-0.test-etcd-headless.vc-test:2380"],"listen-peer-urls":["https://0.0.0.0:2380"],"advertise-client-urls":["https://test-etcd-0.test-etcd-headless.vc-test:2379"],"listen-client-urls":["https://0.0.0.0:2379"],"listen-metrics-urls":["http://0.0.0.0:2381"]}
{"level":"info","ts":"2023-11-20T19:30:33.409527Z","caller":"rafthttp/stream.go:395","msg":"started stream reader with remote peer","stream-reader-type":"stream Message","local-member-id":"1d1c77e4faa2d414","remote-peer-id":"f9b2fae4f5cf40bc"}
{"level":"info","ts":"2023-11-20T19:30:33.409535Z","caller":"rafthttp/stream.go:395","msg":"started stream reader with remote peer","stream-reader-type":"stream MsgApp v2","local-member-id":"1d1c77e4faa2d414","remote-peer-id":"f9b2fae4f5cf40bc"}
{"level":"info","ts":"2023-11-20T19:30:33.409551Z","caller":"embed/etcd.go:855","msg":"serving metrics","address":"http://0.0.0.0:2381"}
{"level":"warn","ts":"2023-11-20T19:30:33.519056Z","caller":"embed/config_logging.go:160","msg":"rejected connection","remote-addr":"100.80.170.236:45114","server-name":"test-etcd-0.test-etcd-headless.vc-test","ip-addresses":["0.0.0.0","127.0.0.1","::1"],"dns-names":["*.test-etcd-headless","*.test-etcd-headless.vc-test","localhost","test-api","test-etcd","test-etcd.vc-test","test-etcd.vc-test.svc"],"error":"tls: \"100.80.170.236\" does not match any of DNSNames [\"*.test-etcd-headless\" \"*.test-etcd-headless.vc-test\" \"localhost\" \"test-api\" \"test-etcd\" \"test-etcd.vc-test\" \"test-etcd.vc-test.svc\"]"}
{"level":"warn","ts":"2023-11-20T19:30:33.522243Z","caller":"embed/config_logging.go:160","msg":"rejected connection","remote-addr":"100.80.107.136:57096","server-name":"test-etcd-0.test-etcd-headless.vc-test","ip-addresses":["0.0.0.0","127.0.0.1","::1"],"dns-names":["*.test-etcd-headless","*.test-etcd-headless.vc-test","localhost","test-api","test-etcd","test-etcd.vc-test","test-etcd.vc-test.svc"],"error":"tls: \"100.80.107.136\" does not match any of DNSNames [\"*.test-etcd-headless\" \"*.test-etcd-headless.vc-test\" \"localhost\" \"test-api\" \"test-etcd\" \"test-etcd.vc-test\" \"test-etcd.vc-test.svc\"]"}
{"level":"warn","ts":"2023-11-20T19:30:33.527375Z","caller":"embed/config_logging.go:160","msg":"rejected connection","remote-addr":"100.80.107.136:57108","server-name":"test-etcd-0.test-etcd-headless.vc-test","ip-addresses":["0.0.0.0","127.0.0.1","::1"],"dns-names":["*.test-etcd-headless","*.test-etcd-headless.vc-test","localhost","test-api","test-etcd","test-etcd.vc-test","test-etcd.vc-test.svc"],"error":"tls: \"100.80.107.136\" does not match any of DNSNames [\"*.test-etcd-headless\" \"*.test-etcd-headless.vc-test\" \"localhost\" \"test-api\" \"test-etcd\" \"test-etcd.vc-test\" \"test-etcd.vc-test.svc\"]"}
```

Services:
```
NAME                      TYPE         CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
dex                       ClusterIP   172.20.116.95    <none>        5556/TCP,5558/TCP   7m35s
test                 ClusterIP   172.20.140.32    <none>        443/TCP,10250/TCP   7m23s
test-api             ClusterIP   172.20.146.120   <none>        443/TCP             7m23s
test-etcd            ClusterIP   172.20.184.3     <none>        2379/TCP,2380/TCP   7m23s
test-etcd-headless   ClusterIP   None             <none>        2379/TCP,2380/TCP   7m23s
```

Secrets:
```
NAME                                TYPE                             DATA   AGE
dex                                     Opaque                           1      3m50s
dex-ingress-tls                   kubernetes.io/tls                2      3m44s
test-image-pull-secret       kubernetes.io/dockerconfigjson   1      3m53s
sh.helm.release.v1.dex.v1   helm.sh/release.v1               1      3m50s
sh.helm.release.v1.test.v1   helm.sh/release.v1               1      3m38s
test-certs                            Opaque                           25     3m32s
```

Pods:
```
NAME                                             READY   STATUS             RESTARTS        AGE
dex-b6985c88b-xfp8k                    1/1     Running            0               8m10s
test-847fb9b9b9-4fql4                   0/1     CrashLoopBackOff   5 (7s ago)      7m58s
test-847fb9b9b9-qlczx                   0/1     CrashLoopBackOff   5 (7s ago)      7m57s
test-api-5c6d74c546-g2xr5            0/1     Running            6 (2m55s ago)   7m58s
test-api-5c6d74c546-mjqb9           0/1     CrashLoopBackOff   5 (2m32s ago)   7m57s
test-controller-7d454ff8b-26vbh   1/1     Running            0               7m57s
test-controller-7d454ff8b-kzbcs    1/1     Running            0               7m58s
test-etcd-0                                      0/1     Running            1 (3m33s ago)   7m57s
test-etcd-1                                      0/1     Running            1 (3m36s ago)   7m57s
test-etcd-2                                      0/1     Running            1 (3m34s ago)   7m57s
```

### What did you expect to happen?

A working cluster

### How can we reproduce it (as minimally and precisely as possible)?

We use vcluster k8s distribution on AWS EKS with cilium CNI with AWS ENI IP addresses. Probably that's the reason of incorrect tls secrets. Oddly enough if I update the vcluster from 0.16.4 to 0.17.0 everything is working. I've tried to restart etcd, but it's still working. The only issue I found is with the new servicemonitor for api metrics, introduced in 0.17.0: prometheus can't connect to the url with the same tls error (addresses like 100.80.162.123 does not match addresses listed in the certificate, e.g. 172.20.105.38)

### Anything else we need to know?

Some configuration:

```
enableHA: true,
serviceCIDR: "172.20.0.0/16",
sync: {
  "services": {
    enabled: true,
  },
  "configmaps": {
    enabled: true,
  },
  "secrets": {
    enabled: true,
  },
  "endpoints": {
    enabled: true,
  },
  "pods": {
    enabled: true,
  },
  "events": {
    enabled: true,
  },
  "persistentvolumeclaims": {
    enabled: true,
  },
  "ingresses": {
    enabled: true,
  },
  "fake-nodes": {
    enabled: false,
  },
  "fake-persistentvolumes": {
    enabled: false,
  },
  "nodes": {
    enabled: true,
    syncAllNodes: true,
    nodeSelector: "",
    enableScheduler: false,
    syncNodeChanges: false,
  },
  "persistentvolumes": {
    enabled: true,
  },
  "hoststorageclasses": {
    enabled: true,
  },
  "storageclasses": {
    enabled: false,
  },
  "priorityclasses": {
    enabled: false,
  },
  "networkpolicies": {
    enabled: false,
  },
  "volumesnapshots": {
    enabled: true,
  },
  "poddisruptionbudgets": {
    enabled: true,
  },
  "serviceaccounts": {
    enabled: true,
  },
proxy: {
  metricsServer: {
    nodes: {
      enabled: true,
    },
    pods: {
      enabled: true,
    },
  },
},
```

### Host cluster Kubernetes version

<details>

```
Server Version: version.Info{Major:"1", Minor:"26+", GitVersion:"v1.26.10-eks-4f4795d", GitCommit:"164dfb62db432c0b28a1fced3956256af68533b6", GitTreeState:"clean", BuildDate:"2023-10-20T23:21:27Z", GoVersion:"go1.20.10", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Host cluster Kubernetes distribution

<details>

```
EKS
```

</details>

### vlcuster version

<details>

```
0.17.0
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
k8s
```

</details>

### OS and Arch

<details>

```
OS: 
Arch:
```
</details>

### PR DESCRIPTION
**Pull request by facchettos**
**What issue type does this pull request address?** (keep at least one, remove the others) 
/kind bugfix

**What does this pull request do? Which issues does it resolve?** (use `resolves #<issue_number>` if possible) 
resolves #1365 
resolves eng-2433 
regression happened in #1336 
**Please provide a short message that should be published in the vcluster release notes**
Fixed an issue where vcluster's etcd would not come up when in HA mode
bugfix: resolves etcd cert issue

**What else do we need to know?**

### CODE REVIEW

File: pkg/setup/initialize.go [hunk 1]
```diff
@@ -138,6 +139,17 @@ func GenerateK8sCerts(ctx context.Context, currentNamespaceClient kubernetes.Int
 		"*." + etcdService + "-headless" + "." + currentNamespace,
 	}
 
+	//expect up to 20 etcd members, number could be lower since more
```
Comment (facchettos) [inline pkg/setup/initialize.go:142]: this is what shouldn't have been remove from the other pr, extra comment is from there https://etcd.io/docs/v3.3/faq/#what-is-maximum-cluster-size

Comment (ishankhare07) [reply pkg/setup/initialize.go:142]: should we go ahead with the current number? I guess its just about expecting at most 20 members and their corresponding SANs and not actually having that many members right?

Comment (facchettos) [reply pkg/setup/initialize.go:142]: yeah it's just a comment, we can modify it later if we want, I just wanted to point that expecting 20 might be overkill

Comment (facchettos) [reply pkg/setup/initialize.go:142]: the part that says that it shouldn't have been removed is the code, not the comment btw

**Review by ishankhare07 — APPROVED** [review]

**Review by ThomasK33 — APPROVED** [review]
