### PR TITLE
fix: remove kubernetes-version flag in vcluster create

### LINKED ISSUE #2294: Vcluster 0.21 seems to not respect `--kubernetes-version`
### What happened?

If I try to create a vcluster with `--kubernetes-version 1.27` in a host cluster running K8s `1.30.4`, the `--kubernetes-version 1.27` flag seems ignored. Nothing is shown in the logs either. The final vcluster k8s version ends up as `1.30.4`.

### What did you expect to happen?

This was working fine on 0.20. I was expecting it to work the same?

### How can we reproduce it (as minimally and precisely as possible)?

```console
$ k3d cluster create # right now it creates a 1.30.4 cluster

$ vcluster create --kubernetes-version 1.27 felipe
17:02:45 info Creating namespace vcluster-felipe
17:02:45 info Chart not embedded: "open chart/vcluster-0.21.1.tgz: file does not exist", pulling from helm repository.
17:02:45 info Create vcluster felipe...
17:02:45 info execute command: helm upgrade felipe https://charts.loft.sh/charts/vcluster-0.21.1.tgz --create-namespace --kubeconfig /tmp/899677600 --namespace vcluster-felipe --install --repository-config='' --values /tmp/3145409311
17:02:47 done Successfully created virtual cluster felipe in namespace vcluster-felipe
17:02:55 info Waiting for vcluster to come up...
17:03:04 info vcluster is waiting, because vcluster pod felipe-0 has status: Init:1/3
17:03:14 info vcluster is waiting, because vcluster pod felipe-0 has status: Init:2/3
17:03:34 done vCluster is up and running
17:03:34 info Starting background proxy container...
17:03:46 done Switched active kube context to vcluster_felipe_vcluster-felipe_k3d-k3s-default
- Use `vcluster disconnect` to return to your previous kube context
- Use `kubectl get namespaces` to access the vcluster

$ vcluster connect felipe -- kubectl version
17:05:08 done vCluster is up and running
Client Version: v1.31.3
Kustomize Version: v5.4.2
Server Version: v1.30.4
```

### Anything else we need to know?

_No response_

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.31.3
Kustomize Version: v5.4.2
Server Version: v1.30.4+k3s1
Kubecolor Version: 0.4.0
```

</details>

### vcluster version

<details>

```console
$ vcluster --version
vcluster version 0.21.1
```

</details>

### VCluster Config

N/A

### PR DESCRIPTION
**Pull request by kale-amruta**
**What issue type does this pull request address?** (keep at least one, remove the others) 
/kind bugfix

**What does this pull request do? Which issues does it resolve?** (use `resolves #<issue_number>` if possible) 
resolves #2294
resolves ENG-5242

**Please provide a short message that should be published in the vcluster release notes**
Remove the `kubernetes-version` flag in `vcluster create`command, kubernetes version can now be configured from values.yaml.

**What else do we need to know?**

### CODE REVIEW

**Comment by felipecrs** [comment]
@kale-amruta, I don't think it makes sense to deprecate something that doesn't even work anymore.

So, I think you should drop all the logic behind this flag and even remove the flag itself.

When using it, it should fail to indicate that it's not supported and avoid the confusion of #2294.

File: pkg/cli/create_helm.go [hunk 1]
```diff
@@ -724,10 +725,6 @@ func (cmd *createHelm) getKubernetesVersion() (*version.Info, error) {
 
 		majorMinorVer := semver.MajorMinor(cmd.KubernetesVersion)
 
-		if splittedVersion := strings.Split(cmd.KubernetesVersion, "."); len(splittedVersion) > 2 {
```
Comment (FabianKramm) [inline pkg/cli/create_helm.go:727]: Whats the reasoning for removing this? Since it is only deprecated we still need that don't we?

**Review by FabianKramm — COMMENTED** [review]
@kale-amruta thanks for the PR! See my comment above

File: pkg/cli/create_helm.go (hunk 1 above)
Comment (felipecrs) [reply pkg/cli/create_helm.go:727]: @FabioKaram, please check the associated issue. There is no point deprecating a feature that doesn't even work.

Comment (FabianKramm) [reply pkg/cli/create_helm.go:727]: @felipecrs yes you are right, we should remove it instead

**Comment by FabianKramm** [comment]
@kale-amruta can you instead of deprecating this flag, remove it instead?

File: pkg/cli/create_helm.go (hunk 1 above)
Comment (kale-amruta) [reply pkg/cli/create_helm.go:727]: @FabianKramm I had thought of removing the flags but there are some other flags eg "distro" which is also not used but is deprecated, which is why I did not remove this flag. If we are okay with removing this flag and related code, I would like to remove ``distro`` flag as well? WDYT?

Comment (FabianKramm) [reply pkg/cli/create_helm.go:727]: @kale-amruta distro is still used internally though while kubernetes-version is not working at all anymore, so I would wait with removing distro flag.

Comment (kale-amruta) [reply pkg/cli/create_helm.go:727]: Ok, makes sense, I will remove just the `kubernetes-version`

**Comment by kale-amruta** [comment]
@FabianKramm Can you re-review this one?

**Review by cbron — DISMISSED** [review]
lgtm, thanks

**Comment by cbron** [comment]
actually, @kale-amruta there are some failing errors from lint here, can you check them

**Review by cbron — APPROVED** [review]
