### PR TITLE
fix: service CIDR retirieval on k8s < v1.20

### LINKED ISSUE #944: K3s failed to start because of configuration error
### What happened?

Using vcluster-0.14.1 CMD to create a vcluster .The service cannot be started and an error is reported .

I found that the correct configuration is correct in 0.14.0

and rong in 0.14.1

### What did you expect to happen?

K3s can be configured correctly

### How can we reproduce it (as minimally and precisely as possible)?

my values.yaml

# Enable HA mode

enableHA: true

# Enable isolation for Security

\#Because there is a privileged container in the AI management service that will not be started temporarily
isolation:
enabled: false
defaultImageRegistry: "[guigu-registry.cucloud.cn/vcluster/](http://guigu-registry.cucloud.cn/vcluster/)"

\#vcluster plugin that is used to sync net-attach-def
plugin:
sync-net-attach-def:
image: vcluster-netattachdef-sync-plugin:0.0.1
imagePullPolicy: IfNotPresent
rbac:
role:
extraRules:
\- apiGroups: \[ "[k8s.cni.cncf.io](http://k8s.cni.cncf.io)" \]
resources: \[ "network-attachment-definitions" \]
verbs: \[ "create", "delete", "patch", "update", "get", "list", "watch" \]
clusterRole:
extraRules:
\- apiGroups: \[ "[apiextensions.k8s.io](http://apiextensions.k8s.io)" \]
resources: \[ "customresourcedefinitions" \]
verbs: \[ "get", "list", "watch" \]
resources:
limits:
memory: 16Gi
requests:
cpu: 200m
memory: 256Mi

# Scale up k3s replicas

replicas: 1
vcluster:
image: k3s:v1.19.16-k3s1
env:

* name: K3S_DATASTORE_ENDPOINT
  value: [https://etcd-cluster-0.etcd-cluster.ai-vcluster-etcd.svc.cluster.local:2379](https://etcd-cluster-0.etcd-cluster.ai-vcluster-etcd.svc.cluster.local:2379),[https://etcd-cluster-1.etcd-cluster.ai-vcluster-etcd.svc.cluster.local:2379](https://etcd-cluster-1.etcd-cluster.ai-vcluster-etcd.svc.cluster.local:2379),[https://etcd-cluster-2.etcd-cluster.ai-vcluster-etcd.svc.cluster.local:2379](https://etcd-cluster-2.etcd-cluster.ai-vcluster-etcd.svc.cluster.local:2379)
* name: K3S_DATASTORE_CAFILE
  value: '/tls/cacert'
* name: K3S_DATASTORE_CERTFILE
  value: '/tls/cert'
* name: K3S_DATASTORE_KEYFILE
  value: '/tls/key'
  volumeMounts:
  * mountPath: /data
    name: data
  * mountPath: /tls
    name: datastore-tls
    volumes:
* name: datastore-tls
  secret:
  secretName: etcd-tls
  items:
  * key: [tls.ca](http://tls.ca)
    path: cacert
  * key: tls.crt
    path: cert
  * key: tls.key
    path: key
    sync:
    pods:
    enabled: true

  # Sync ephemeralContainers to host cluster

  ephemeralContainers: true

  # Sync readiness gates to host cluster

  status: true
  nodes:
  enabled: true
  enableScheduler: true
  nodeSelector: "ai-vclusternode=node"
  csistoragecapacities:
  enabled: false
  csidrivers:
  enabled: false
  csinodes:
  enabled: false
  syncer:
  image: vcluster:0.14.1
  extraArgs:
  * --tls-san=101.44.4.190,172.31.2.124,172.31.2.125,172.31.2.126
    \#Automatically add tolerance for stains
    \#- --enforce-toleration=key1=value1:NoSchedule
    storage:
    persistence: false
    coredns:
    replicas: 1

### Anything else we need to know?

*No response*

### Host cluster Kubernetes version

<details>

```
$ kubectl version
# paste output here
```

</details>

### Host cluster Kubernetes distribution

<details>

```
# Write here
```

</details>

### vlcuster version

<details>

```
$ vcluster --version
# paste output here
```

vcluster version 0.14.0
</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
# Write here
```

</details>
k3s

### OS and Arch

<details>

```
OS: 
Arch:
```

</details>
centos 7

### PR DESCRIPTION
**Pull request by matskiv**
**What issue type does this pull request address?** (keep at least one, remove the others) 
/kind bugfix

**What does this pull request do? Which issues does it resolve?** (use `resolves #<issue_number>` if possible) 
resolves #944 

**Please provide a short message that should be published in the vcluster release notes**
Fixed an issue where vcluster would not start on a Kubernetes v1.20 and older due to wrong Service CIDR detection.

**What else do we need to know?** 
The problem was reproducible only on Kubernetes v1.20 and earlier.

### CODE REVIEW

File: pkg/util/servicecidr/servicecidr.go [hunk 1]
```diff
@@ -197,5 +197,18 @@ func getServiceCIDR(client kubernetes.Interface, namespace string, ipv6 bool) (s
 		return "", fmt.Errorf("couldn't find host cluster Service CIDR (\"%s\")", errorMessage)
 	}
 
-	return strings.TrimSpace(errorMessage[idx+len(ErrorMessageFind):]), nil
+	cidr := strings.TrimSpace(errorMessage[idx+len(ErrorMessageFind):])
+	ip, _, err := net.ParseCIDR(cidr)
+	if err != nil {
+		return "", err
+	}
+	isIPv4 := ip.To4() != nil
```
Comment (matskiv) [inline pkg/util/servicecidr/servicecidr.go:205]: This^ is a key piece. Quoting [docs](https://pkg.go.dev/net#IP.To4):
> To4 converts the IPv4 address ip to a 4-byte representation. If ip is not an IPv4 address, To4 returns nil.

**Review by FabianKramm — APPROVED** [review]
