### PR TITLE
fix: add vcluster port-forward command to use as the background proxy…

### LINKED ISSUE #2838: Background-proxy docker container exit itself after kubectl error
### What happened?

When vcluster is deployed with `--background-proxy` (true by default), it will try to deploy if possible a docker container in background, that will exist normally until we do `vcluster disconnect`.

However when we do a `kubectl` that ends in error, the vcluster container exit itself, with no obvious cause, and any subsequent `kubectl` is in error with:
```
The connection to the server 127.0.0.1:11413 was refused - did you specify the right host or port?
```
This `kubectl` error can be done on purpose, like to probe if a container is ready. It should not result in a vcluster exiting itself.

However this behavior is not reproducible when `--background-proxy=false` is used, which is the behavior in old release (e.g.: v0.18.0).
Workaround: deploy vcluster with `--background-proxy=false`

### What did you expect to happen?

The vcluster background proxy container should never exit itself, unless a `vcluster disconnect` is submitted (or obviously if someone does a `docker rm`).

### How can we reproduce it (as minimally and precisely as possible)?

1. deploy vcluster with default parameter, in a VM with docker running
2. deploy any pod (helloworld pod)
3. do `kubectl exec -ti deploy/helloworld -- not_existing_command` which will result in "command not found in $PATH".
4. redo step 3. Now the error is a connection error with vcluster background proxy

### Anything else we need to know?

_No response_

### Host cluster Kubernetes version

v1.32.1

### vcluster version

0.25.0

### VCluster Config

Ask me if really needed. Any default config.

### PR DESCRIPTION
**Pull request by lizardruss**
… process until https://github.com/containerd/containerd/issues/9875 is resolved

**What issue type does this pull request address?** (keep at least one, remove the others) 
/kind bugfix

**What does this pull request do? Which issues does it resolve?** (use `resolves #<issue_number>` if possible) 
resolves #2838
resolves ENG-7008

**Please provide a short message that should be published in the vcluster release notes**
Fixed an issue where vcluster's background proxy's port-forwarding could be interrupted due to unexpected errors from the container sandbox starting with containerd 2.x

**What else do we need to know?**
- `port-forward` command was "fork lifted" from `kubectl` and adapted to work with the vcluster command
- `pkg/util/portforward/portforward.go` was brought up to date with the client-go version with some minor changes

### CODE REVIEW

File: pkg/constants/cli.go [hunk 1]
```diff
@@ -1,3 +1,3 @@
 package constants
 
-const DefaultBackgroundProxyImage = "bitnami/kubectl:1.33"
+const DefaultBackgroundProxyImage = "ghcr.io/loft-sh/vcluster:dev-next"
```
Comment (hidalgopl) [inline pkg/constants/cli.go]: were you able to pinpoint which container runtime version / kubernetes version has this issue? Asking because when I initially started on this, I assumed it's only for containerd v2, so I've added a code that was detecting the container runtime version and using this workaround only for these, and bitnami image for everything else.

Not sure if it's needed, we can also document it & ask user to pass `--background-proxy-image=ghcr.io/loft-sh/vcluster ...` it they use certain version matrix.
Anyway, posting what I had in `pkg/cli/connect_helm.go#getVClusterKubeConfig` just in case you decide it's needed to detect and swap background proxy image dynamically:
```go
podNodeName = pods.Items[0].Spec.NodeName
node, err := cmd.kubeClient.CoreV1().Nodes().Get(ctx, podNodeName, metav1.GetOptions{})
if err != nil {
    return nil, err
}
if strings.HasPrefix(node.Status.NodeInfo.ContainerRuntimeVersion, "containerd://") {
    containerdVer := semver.MustParse(node.Status.NodeInfo.ContainerRuntimeVersion)
        if containerdVer.GTE(semver.MustParse("2.0.0")) {
		cmd.BackgroundProxyImage = "ghcr.io/loft-sh/vcluster:dev-next"
	}
}
```

Comment (lizardruss) [reply pkg/constants/cli.go]: Based on the upstream PR comment ([copied here](https://github.com/loft-sh/vcluster/pull/2872/files#diff-86e08599fc7ded2881fc3ac7b17d11c549636ca5f16814d787ff19393e771f5eR53-R56)), it looks like it affects containerd 1.7, 2x+, and CRI-O 1.31

**Review by FabianKramm — APPROVED** [review]

**Comment by lizardruss** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|v0.25|[](https://github.com/loft-sh/vcluster/pull/2875)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

**Comment by lizardruss** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|v0.24|[](https://github.com/loft-sh/vcluster/pull/2876)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

**Comment by lizardruss** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|v0.23|[](https://github.com/loft-sh/vcluster/pull/2877)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
