### PR TITLE
fix node labels syncing

### LINKED ISSUE #1001: Node label kubernetes.io/hostname should contain correct value
### What happened?

When "fake nodes" sync is used, we set a fake hostname (fake-$NAME) in `kubernetes.io/hostname` Node label.

### What did you expect to happen?

We should set the value of `kubernetes.io/hostname` to the `$NAME.nodes.vcluster.com`([*GetNodeHost()*](https://github.com/loft-sh/vcluster/blob/c0cfca75b2fe547663f4e1a04407a38b22a5913a/pkg/controllers/resources/nodes/fake_syncer.go#L323)) instead.
This should also be done for the "real nodes sync".

### How can we reproduce it (as minimally and precisely as possible)?

```
vcluster create vc -n vc
# in vcluster kube context:
kubectl get nodes --label-columns="kubernetes.io/hostname"
```

### Anything else we need to know?

*No response*

### Host cluster Kubernetes version

N/A

### Host cluster Kubernetes distribution

N/A

### vlcuster version

v0.15.0-beta.0

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

N/A

### OS and Arch

N/A

### PR DESCRIPTION
**Pull request by ishankhare07**
**What issue type does this pull request address?** (keep at least one, remove the others) 
/kind bugfix
/kind enhancement
/kind test

**What does this pull request do? Which issues does it resolve?** (use `resolves #<issue_number>` if possible) 
resolves #1001 ENG-1289

**Please provide a short message that should be published in the vcluster release notes**
Fixed an issue where vcluster node were syncing as `fake-$NAME`. Use `$NAME.nodes.vcluster.com` instead

**What else do we need to know?**

### CODE REVIEW

**Review by FabianKramm — CHANGES_REQUESTED** [review]

File: pkg/controllers/resources/nodes/translate.go [hunk 1]
```diff
@@ -90,6 +90,7 @@ func (s *nodeSyncer) translateUpdateBackwards(pNode *corev1.Node, vNode *corev1.
 		}
 	} else {
 		labels, annotations = translate.ApplyMetadata(pNode.Annotations, vNode.Annotations, pNode.Labels, vNode.Labels)
+		labels["kubernetes.io/hostname"] = GetNodeHost(vNode.Name)
```
[the remark this answers is not in the document]
Comment (ishankhare07) [reply pkg/controllers/resources/nodes/translate.go]: Hi @FabianKramm actually the original issue also mentioned
> This should also be done for the "real nodes sync".

And yea I think I added the above line at the wrong place, I will move it out of the if-else block – we should not be ignoring the `enableScheduler` path, thanks for pointing out

File: pkg/controllers/resources/nodes/translate.go [hunk 2]
```diff
@@ -98,8 +98,11 @@ func (s *nodeSyncer) translateUpdateBackwards(pNode *corev1.Node, vNode *corev1.
 		} else {
 			delete(annotations, TaintsAnnotation)
 		}
+		labels, annotations = translate.ApplyMetadata(pNode.Annotations, vNode.Annotations, pNode.Labels, vNode.Labels)
```
Comment (FabianKramm) [inline pkg/controllers/resources/nodes/translate.go:101]: Why is that needed here?

**Review by FabianKramm — CHANGES_REQUESTED** [review]

File: pkg/controllers/resources/nodes/translate.go [hunk 3]
```diff
@@ -100,6 +100,8 @@ func (s *nodeSyncer) translateUpdateBackwards(pNode *corev1.Node, vNode *corev1.
 		}
 	}
 
+	labels["kubernetes.io/hostname"] = GetNodeHost(vNode.Name)
```
Comment (FabianKramm) [inline pkg/controllers/resources/nodes/translate.go:103]: I think we should only do this if `s.useFakeKubelets` is true as otherwise we won't rewritte the hostname at all

**Review by FabianKramm — CHANGES_REQUESTED** [review]

**Review by FabianKramm — APPROVED** [review]
