### PR TITLE
fix: affinity label selector overriden by namespace selector

### LINKED ISSUE #1484: anti affinity missing on synced pod if namespace selector matches all namespaces
### What happened?

We are installing multiple charts in different namespaces, and for some pods, they need pod anti affinity across all the namespaces, to make sure no two pods from the same role are scheduled to the same node.

```
affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: sfcn.cisco.com/enforcement-point
                operator: Exists
          topologyKey: kubernetes.io/hostname
          namespaceSelector: {}
```

The "[sfcn.cisco.com/enforcement-point](http://sfcn.cisco.com/enforcement-point)" label is used to indicate the pod is an enforcer role, and no two enforcer pods should be scheduled to the same node, regardless of namespace.
However, when this pod is synced to the host cluster, the "[sfcn.cisco.com/enforcement-point](http://sfcn.cisco.com/enforcement-point)" label is missing. We are seeing the following anti affinity rule, which matches all the pods installed in the corresponding vcluster.

```
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              vcluster.loft.sh/managed-by: <vcluster-name>
          topologyKey: kubernetes.io/hostname
```

### What did you expect to happen?

I expect to see the matchExpressions preserved in the synced pod

```
matchExpressions:
    - key: sfcn.cisco.com/enforcement-point
      operator: Exists
```

### How can we reproduce it (as minimally and precisely as possible)?

Create a pod using the following spec in a vcluster

```
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: aws-cli
      image: amazon/aws-cli:latest
      command:
        - /bin/bash
        - '-c'
        - sleep infinity
      imagePullPolicy: Always
  affinity:
    podAntiAffinity:  
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: sfcn.cisco.com/enforcement-point
                operator: Exists
          topologyKey: kubernetes.io/hostname
          namespaceSelector: {}
```

Go to the host cluster, read the pod spec, you'll have the following affinity config

```
affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              vcluster.loft.sh/managed-by: <vcluster-name>
          topologyKey: kubernetes.io/hostname
```

### Anything else we need to know?

*No response*

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.16", GitCommit:"c5f43560a4f98f2af3743a59299fb79f07924373", GitTreeState:"clean", BuildDate:"2023-11-15T22:39:12Z", GoVersion:"go1.20.10", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25+", GitVersion:"v1.25.16-eks-8cb36c9", GitCommit:"3a3ea80e673d7867f47bdfbccd4ece7cb5f4a83a", GitTreeState:"clean", BuildDate:"2023-11-22T21:53:22Z", GoVersion:"go1.20.10", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Host cluster Kubernetes distribution

<details>

```
EKS
```

</details>

### vlcuster version

<details>

```console
$ vcluster --version
vcluster version 0.18.1
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
vcluster-eks
```

</details>

### OS and Arch

<details>

```
OS: N/A
Arch: N/A
```

</details>

### PR DESCRIPTION
**Pull request by rohantmp**
- chore: go mod tidy && go mod vendor
- fix: affinity label selector overriden by namespace selector

**What issue type does this pull request address?** (keep at least one, remove the others) 
/kind bugfix

**What does this pull request do? Which issues does it resolve?** (use `resolves #<issue_number>` if possible) 
part-of ENG-2759
fixes #1484

**Please provide a short message that should be published in the vcluster release notes**
Fixed an issue where vcluster mistranslated affinity terms.

**What else do we need to know?**

### CODE REVIEW

**Comment by rohantmp** [comment]
Will rebase on master, the base is currently 19 (should be fine, but will test rebased on master)

**Comment by FabianKramm** [comment]
Hey @rohantmp! Can you explain how this solves the problem?

**Comment by rohantmp** [comment]
Since we translate into a single namespace, the namespace selector was being translated into a labelselector based on the vcluster namespace labels, so it would override any translated labelselectors. Now this merges the translated label selector and the translated namespace selector into labelselectors

**Comment by rohantmp** [comment]
verified the behavior locally too

File: pkg/controllers/resources/pods/translate/translator_test.go [hunk 1]
```diff
@@ -115,20 +124,34 @@ func TestPodAffinityTermsTranslation(t *testing.T) {
...
+		if testCase.focus {
+			isFocused = true
+			break
+		}
+	}
+
 	for _, testCase := range testCases {
+		if isFocused && !testCase.focus {
+			continue
+		}
```
Comment (facchettos) [inline pkg/controllers/resources/pods/translate/translator_test.go:154]: what is this for? selecting only a subset of tests to be run when developing?

Comment (rohantmp) [reply pkg/controllers/resources/pods/translate/translator_test.go:154]: Yup, it fails at the end if any tests are focused.

File: pkg/controllers/resources/pods/translate/translator_test.go [hunk 2]
```diff
@@ -150,13 +173,17 @@ func TestPodAffinityTermsTranslation(t *testing.T) {
 
 		assert.Assert(t, cmp.DeepEqual(events, testCase.expectedEvents), "Unexpected Event in the '%s' test case", testCase.name)
 	}
+
+	assert.Assert(t, !isFocused, "test should not be focused, but if you've hit this, focused tests pass!")
```
Comment (rohantmp) [inline pkg/controllers/resources/pods/translate/translator_test.go:177]: @facchettos here

File: pkg/controllers/resources/pods/translate/translator_test.go (hunk 1 above)
Comment (facchettos) [reply pkg/controllers/resources/pods/translate/translator_test.go:154]: not sure I am a fan of this :D what's wrong with `go test -v` or something similar?
I think the issue here is that it's not using table driven test properly, because you'd have a proper breakdown of what tests failed with something like this 
```go

func Test(t *testing.T) {
	testCases := []struct {
		desc	string
		
	}{
		{
			desc: "",
			
		},
	}
	for _, tC := range testCases {
		t.Run(tC.desc, func(t *testing.T) {
			
		})
	}
}
```

Comment (facchettos) [reply pkg/controllers/resources/pods/translate/translator_test.go:154]: what do you mean? `Also, sometimes you can't get to the test case you're trying to game out until you make the previous ones pass` 
You can absolutely do that with `t.Run` 

` this code doesn't do anything till the next person has to fiddle with the tests` so it's essentially dead code no? And you can also use `go test -v -run Test/subtest` (with $ if you have subtest, subtest_something, etc so it only runs a complete match)

Comment (rohantmp) [reply pkg/controllers/resources/pods/translate/translator_test.go:154]: Ahh, right. Didn't know you could use `-run Test/subtest` removing :)

**Review by FabianKramm — APPROVED** [review]
