### PR TITLE
Fix api service reg

### LINKED ISSUE #1163: Deletion of namespace hangs when proxying metrics-server
### What happened?

Installed a vcluster using helm chart vcluster-k8s-0.15.5.tgz. Enabled proxy for metrics-server.

I then connect to the vcluster, and try to delete a namespace, even if it's newly created and empty, this happens:
```
Name:         testing
Labels:       kubernetes.io/metadata.name=testing
Annotations:  <none>
Status:       Terminating
Conditions:
  Type                                         Status  LastTransitionTime               Reason                  Message
  ----                                         ------  ------------------               ------                  -------
  NamespaceDeletionDiscoveryFailure            True    Thu, 17 Aug 2023 13:58:06 +0200  DiscoveryFailed         Discovery failed for some groups, 1 failing: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server could not find the requested resource
  NamespaceDeletionGroupVersionParsingFailure  False   Thu, 17 Aug 2023 13:58:06 +0200  ParsedGroupVersions     All legacy kube types successfully parsed
  NamespaceDeletionContentFailure              False   Thu, 17 Aug 2023 13:58:06 +0200  ContentDeleted          All content successfully deleted, may be waiting on finalization
  NamespaceContentRemaining                    False   Thu, 17 Aug 2023 13:58:06 +0200  ContentRemoved          All content successfully removed
  NamespaceFinalizersRemaining                 False   Thu, 17 Aug 2023 13:58:06 +0200  ContentHasNoFinalizers  All content-preserving finalizers finished

No resource quota.

No LimitRange resource.
```

### What did you expect to happen?

That I should be able to delete the namespace without messing with namespace finalizers.

### How can we reproduce it (as minimally and precisely as possible)?

Install vcluster
`helm install vcluster vcluster-k8s-0.15.5.tgz -f values.yaml`

values.yaml:
```
proxy:
  metricsServer:
    nodes:
      enabled: true
    pods:
      enabled: true

sync:
  nodes:
    enabled: true
    syncAllNodes: true
  ingresses:
    enabled: true

enableHA: true

syncer:
  image: ghcr.io/loft-sh/vcluster:0.15.5
  replicas: 3

etcd:
  image: registry.k8s.io/etcd:3.5.7-0
  replicas: 3

controller:
  image: registry.k8s.io/kube-controller-manager:v1.24.14
  replicas: 3

api:
  image: registry.k8s.io/kube-apiserver:v1.24.14
  replicas: 3

coredns:
  image: coredns/coredns:1.10.1
  replicas: 3

service:
  type: LoadBalancer
```

`vcluster connect vcluster`
`kubectl create ns testing`
`kubectl delete ns testing`

### Anything else we need to know?

_No response_

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.10", GitCommit:"5c1d2d4295f9b4eb12bfbf6429fdf989f2ca8a02", GitTreeState:"clean", BuildDate:"2023-01-18T19:15:31Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.10+vmware.1", GitCommit:"b980a736cbd2ac0c5f7ca793122fd4231f705889", GitTreeState:"clean", BuildDate:"2023-01-24T15:29:49Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Host cluster Kubernetes distribution

<details>

```
Tanzu Kubernetes Grid Integrated Edition 1.15.x
```
But it's not isolated to TKGI. Happens even in a Kubernetes Kind cluster.

</details>

### vlcuster version

<details>

```console
$ vcluster --version
vcluster version 0.15.5
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
k8s
```

</details>

### OS and Arch

<details>

```
OS: Ubuntu Xenial
Arch: x64
```

When running in Kind:
```
OS: RHEL7
Arch: x64
```
</details>

### PR DESCRIPTION
**Pull request by ishankhare07**
**What issue type does this pull request address?** (keep at least one, remove the others) 
/kind bugfix
/kind enhancement

**What does this pull request do? Which issues does it resolve?** (use `resolves #<issue_number>` if possible) 
resolves #1163  ENG-1901

**Please provide a short message that should be published in the vcluster release notes**
Fixed an issue where vcluster when deployed with k8s/eks distro and metrics proxy enabled could not resolve apiservice properly because syncer and apiserver being in separate pods

**What else do we need to know?**

### CODE REVIEW

File: pkg/specialservices/proxy_service_syncer.go [hunk 1]
```diff
@@ -0,0 +1,96 @@
...
+	PhysicalSvcSelectorKeyApp              = "app"
+	PhysicalSvcSelectorKeyRelease          = "release"
+	PhysicalMetricsServerServiceNameSuffix = "-metrics-proxy"
+)
+
+func SyncVclusterProxyService(ctx *synccontext.SyncContext,
+	_,
+	svcName string,
+	vSvcToSync types.NamespacedName,
+	_ ServicePortTranslator) error {
```
Comment (FabianKramm) [inline pkg/specialservices/proxy_service_syncer.go:30]: Can we format this:
```
func SyncVClusterProxyService(
       ctx *synccontext.SyncContext,
	_,
	svcName string,
	vSvcToSync types.NamespacedName,
	_ ServicePortTranslator,
) error {
```

File: charts/eks/templates/metrics-proxy.yaml [hunk 2]
```diff
@@ -0,0 +1,59 @@
...
+      protocol: TCP
+    - name: kubelet
+      port: 10250
+      targetPort: 8443
+      protocol: TCP
+  selector:
+    app: vcluster
+    release: {{ .Release.Name }}
+---
+apiVersion: v1
```
Comment (FabianKramm) [inline charts/eks/templates/metrics-proxy.yaml:31]: Why do we need this config map?

File: charts/eks/templates/syncer-deployment.yaml [hunk 3]
```diff
@@ -169,6 +174,7 @@ spec:
           {{- end }}
           {{- if or .Values.proxy.metricsServer.nodes.enabled .Values.proxy.metricsServer.pods.enabled}}
           - --proxy-metrics-server=true
+          - --single-binary-distro=false
```
Comment (FabianKramm) [inline charts/eks/templates/syncer-deployment.yaml:177]: Why do we have an env var and flag for this? Also why is this necessary?

**Review by FabianKramm — CHANGES_REQUESTED** [review]

File: charts/eks/templates/metrics-proxy.yaml [hunk 4]
```diff
@@ -0,0 +1,59 @@
+{{- if or .Values.proxy.metricsServer.nodes.enabled .Values.proxy.metricsServer.pods.enabled }}
```
Comment (FabianKramm) [inline charts/eks/templates/metrics-proxy.yaml:1]: I think I would prefer to move this out of the helm chart and into the code here

**Comment by FabianKramm** [comment]
@ishankhare07 also would be good if we add some sort of test here to avoid breaking this in future

File: charts/eks/templates/syncer-deployment.yaml (hunk 3 above)
Comment (ishankhare07) [reply charts/eks/templates/syncer-deployment.yaml:177]: this info is needed at 2 places basically, one is at places like endpoints syncer, apiregistration etc.
and the other is in [specialservices](https://github.com/loft-sh/vcluster/pull/1337/files#diff-7daa660cd5210e66fb754f6f39c71db5b72775919140a81c1f376ea9cd4e0d7aR51)

Since we don't have a way to inject controller context here, I thought to inject the env var

File: pkg/controllers/k8sdefaultendpoint/k8sdefaultendpoint.go [hunk 5]
```diff
@@ -67,6 +71,14 @@ func (e *EndpointController) Reconcile(ctx context.Context, _ ctrl.Request) (ctr
 	if err != nil {
 		return ctrl.Result{RequeueAfter: time.Second}, err
 	}
+
+	// TODO: Change this to only be set for k8s/eks distros and when using metrics proxy
```
Comment (ThomasK33) [inline pkg/controllers/k8sdefaultendpoint/k8sdefaultendpoint.go:75]: Was this TODO forgotten or a marker for a later task/issue?

File: test/e2e_metrics_proxy/metricsProxy.go [hunk 6]
```diff
@@ -0,0 +1,36 @@
...
+
+			if apiService.Status.Conditions[0].Type != apiregistrationv1.Available {
+				return false, nil
+			}
+
+			return true, nil
+		})
+		framework.ExpectNoError(err)
+	})
+})
```
Comment (ThomasK33) [inline test/e2e_metrics_proxy/metricsProxy.go:36]: Could we add an additional test performing a request to the metrics API and check wether the response is valid?

File: charts/eks/templates/syncer-deployment.yaml (hunk 3 above)
Comment (ThomasK33) [reply charts/eks/templates/syncer-deployment.yaml:172]: Also, would it make more sense to pass down the name of the distro as an arg instead of this flag and then decide within the code if it's a single binary distro?

**Comment by ishankhare07** [comment]
https://github.com/loft-sh/vcluster/pull/1337#discussion_r1384742108

The `DefaultNameserverFinder` function is not called explicitly anywhere and is implicitly called on package import.
Also the .pro code depends on it and is supposed to override it in case integrated coredns is used over there.

We are still storing the boolean in the controllerctx and using it where possible. But if we want to pass it to `DefaultNameserverFinder` we need to be explicitly calling it in OSS somewhere and also when calling it in Pro, based on the flag we have to call it as default or reset it in case

**Review by ThomasK33 — APPROVED** [review]

File: pkg/controllers/k8sdefaultendpoint/k8sdefaultendpoint.go [hunk 7]
```diff
@@ -94,6 +116,82 @@ func (e *EndpointController) SetupWithManager(mgr ctrl.Manager) error {
...
+			Namespace: specialservices.VclusterProxyMetricsSvcKey.Namespace,
+			Name:      specialservices.VclusterProxyMetricsSvcKey.Name,
+		},
+	}
+
+	result, err := controllerutil.CreateOrPatch(ctx, virtualClient, vEndpoints, func() error {
+		if vEndpoints.Labels == nil {
+			vEndpoints.Labels = map[string]string{}
+		}
+		// vEndpoints.Labels[discoveryv1.LabelSkipMirror] = "true"
```
Comment (FabianKramm) [inline pkg/controllers/k8sdefaultendpoint/k8sdefaultendpoint.go:145]: why is this commented out?

**Review by FabianKramm — APPROVED** [review]
